import Link from "next/link"

export default function Changelog() {
    return (
        <article 
            id="changelog"
            className="about-section"
        >

            <h1 className="about-section-h1">
                Changelog
            </h1>
            <p>
                Improvements will be noted here as they arrive.
            </p>

            <section>
                <h2 className="changelog-version-heading">v1.0 - opening the cove to visitors</h2>
                <p className="changelog-date">Jan 5th 2026</p>
                <ul>
                    <li>
                        No accounts, no tracking, and no data collection beyond the letter a writer chooses to share. 
                    </li><li>
                        Visitors can browse and read letters quietly, without metrics.
                    </li><li>
                        Long letters are shortened on the landing page, and presented in full when selected.
                    </li><li>
                        Letters follow a simple structure: the letter itself, an optional intended recipient, an optional sign-off, and a submission date.
                    </li><li>
                        Writers can experience a guided writing experience with Cove - this space&apos;s quiet AI presence - 
                        though letters cannot yet be submitted.
                    </li><li>
                        Guided writing conversations are moderated by Cove for safety in line with <Link href="/about">guidelines stated here</Link>.
                    </li><li>
                        This website can be navigated using keyboard-only controls, with screen reader support and is mobile-friendly.
                    </li><li>
                        Basic errors from third-party services are surfaced to visitors and writers.
                    </li><li>
                        Clear channels created for contact and support, 
                        including anonymous contact via a third-party provider and direct email.
                    </li>
                </ul>
                <p>
                    This marks the initial opening of the space - small, intentional, and held with care.
                </p>
            </section>

            <section>
                <h2 className="changelog-version-heading">v1.1 - helping visitors settle better</h2>
                <p className="changelog-date">Jan 19th 2026</p>
                <ul>
                    <li>
                        Letters that have been generated by AI has been clearly marked with a tag.
                    </li><li>
                        Repopulated the archive with a curated range of letters reflecting broader relationship types and emotional tones.
                    </li><li>
                        AI-generated letters are now tagged with their emotional tone and relationship focus, offering a clearer sense of what each letter explores at a glance.
                    </li>
                </ul>
                <p>
                    This update deepens the emotional texture of the space - not by adding more, but by being more precise about what&apos;s already here.
                </p>
            </section>

        </article>
    )
}
